spring.application.name=ms-gestionatencionmedica
server.port=${PORT:8190}

# Eureka
eureka.client.service-url.default-zone=${EUREKA_URL:http://localhost:8761/eureka}

# Feign
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000
